# Session 7.0: Building a Table Row by Row
Date: 09/09/2026

In [4]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/eurovision_contestants.csv'
eurovision = pd.read_csv(url)

contests = eurovision[eurovision['year'] != 2020].copy()
contests['decade'] = (contests['year'] / 10).astype(int) * 10

In [5]:
scores = pd.DataFrame(
    {  # dictionary of lists: each column is defined all at once
        "country": ["Norway", "Sweden", "Malta"],  # col1
        "entries": [58, 59, 32],                   # col2
    }
)

scores

  country  entries
0  Norway       58
1  Sweden       59
2   Malta       32

In [6]:
# this is just a nother way to do that using a list of dictionaries
pd.DataFrame(
    [  # list of dictionaries: each row is defined all at once:
        {"country": "Norway", "entries": 58},  # row 1
        {"country": "Sweden", "entries": 59},  # row 2
        {"country": "Malta", "entries": 32},   # row 3
    ]
)

  country  entries
0  Norway       58
1  Sweden       59
2   Malta       32

In [ ]:
# builing a list of dictionaries with a for loop
records = [] # Step 1: Start with an empty list.

for decade, decade_data in contests.groupby('decade'): 
    records.append({  # Step 2: append one dictionary per group inside the loop
        'decade': decade,
        'entries': len(decade_data),
        'countries': decade_data['to_country'].nunique()
    })

pd.DataFrame(records) # Step 3: Turn the finished list into a DataFrame

In [ ]:
# so who who has the most points per decade? 

winners = []

for decade, decade_data in contests.groupby("decade"):
    # Find the average points_final by country in each decade:
    means = decade_data.groupby("to_country")["points_final"].mean()

    # Count the number of times a country was in the finals in each decade:
    counts = decade_data.groupby("to_country")["points_final"].count()

    # What is the index (country) associated with the max avg. points_final in each decade?
    best = means.idxmax()
    print(f"{decade} best country was {best}")

    # Append this decade to our winners list:
    winners.append(
        {
            "decade": decade, # Current decade
            "country": best,  # Country that had highest avg. points_final for this decade
            "finals": counts[best],  # The number of times this country was in the finals
            "mean_points": means[best], # The average points_final for this country
        }
    )

decade_winners = pd.DataFrame(winners) # Turn our list of dictionaries into a dataframe

decade_winners