# Day 2: Session 2A - Reading Data into pandas

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2a_reading_data.html)

Date: 09/01/2026

In [2]:
import pandas as pd

In [ ]:
url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'
goleta = pd.read_csv(url)

url2 = 'https://eds-217-essential-python.github.io/data/openaq_santa_barbara_measurments.csv'
santa_barbara = pd.read_csv(url2)

santa_barbara.head(10)

goleta['value'].mean()

type(goleta['value'].max())

type(goleta['unit'].unique())

type(goleta['parameter'])

goleta['parameter'].head()

goleta.columns

golcolnames = goleta.columns.tolist() # .tolist() changes an index to an actual list duuh

golcolnames

goleta['parameter'].unique()

parawecareabout = ['o3', 'pm25']

goleta.iloc[1,2] #indexing by position for a df requires .iloc

len(goleta.columns) # len() gives length of objext by rows

keep = ['location_name', 'parameter','value', 'unit']
smallgol = goleta[keep]

     location_name parameter   value   unit
0           Goleta        o3   0.025    ppm
1           Goleta        o3   0.028    ppm
2           Goleta        o3   0.029    ppm
3           Goleta        o3   0.027    ppm
4           Goleta        o3   0.026    ppm
...            ...       ...     ...    ...
1957        Goleta      pm25  10.000  µg/m³
1958        Goleta      pm25   8.000  µg/m³
1959        Goleta      pm25   8.000  µg/m³
1960        Goleta      pm25   9.000  µg/m³
1961        Goleta      pm25   5.000  µg/m³

[1962 rows x 4 columns]

In [14]:
goletautc = pd.read_csv(url, index_col = 'datetimeUtc')

goletautc

# goletautc.index.nunique()

,location_id,location_name,parameter,value,unit,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
datetimeUtc,,,,,,,,,,,,,,
2024-07-12T01:00:00+00:00,1186,Goleta,o3,0.025,ppm,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T02:00:00+00:00,1186,Goleta,o3,0.028,ppm,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T03:00:00+00:00,1186,Goleta,o3,0.029,ppm,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T04:00:00+00:00,1186,Goleta,o3,0.027,ppm,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-07-12T05:00:00+00:00,1186,Goleta,o3,0.026,ppm,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-11T20:00:00+00:00,1186,Goleta,pm25,10.000,µg/m³,2024-08-11T13:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-08-11T21:00:00+00:00,1186,Goleta,pm25,8.000,µg/m³,2024-08-11T14:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-08-11T22:00:00+00:00,1186,Goleta,pm25,8.000,µg/m³,2024-08-11T15:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-08-11T23:00:00+00:00,1186,Goleta,pm25,9.000,µg/m³,2024-08-11T16:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2024-08-12T00:00:00+00:00,1186,Goleta,pm25,5.000,µg/m³,2024-08-11T17:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

# Day 2: Session 2B - Exploring a DataFrame

[Session Webpage](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/2b_exploring_data.html)

Date: 09/01/2026

In [ ]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'

In [19]:
goleta.head() # shows first values of df
goleta.tail() # shows last values of df
goleta.shape # shows size of rows and columns
goleta.dtypes # says what each column type is
goleta.info() # says a summary of everything above, its the best

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1962 entries, 0 to 1961
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    1962 non-null   int64
 1   location_name  1962 non-null   object
 2   parameter      1962 non-null   object
 3   value          1962 non-null   float64
 4   unit           1962 non-null   object
 5   datetimeUtc    1962 non-null   object
 6   datetimeLocal  1962 non-null   object
 7   timezone       1962 non-null   object
 8   latitude       1962 non-null   float64
 9   longitude      1962 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     1962 non-null   object
 14  provider       1962 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 230.1+ KB

In [29]:
santa_barbara.info()
santa_barbara.describe() # this gives us all kinds of summary statistics like mean, min max etc
santa_barbara['unit'].unique()

santa_barbara['parameter'].value_counts() # this tells us which values show up, and how often. good for columns with text for values and not numbers

# below is creating a dictionary, which can be used for renaming things or creating a key:value relationship for anything

new_names = {
    'datetimeUtc': 'datetime_utc',
    'datetimeLocal': 'datetime_local',
}

goleta_renamed = goleta.rename(columns=new_names) # this renames the two columns that are stored in the dictionary
goleta_renamed.head()

goleta.rename(columns={'value': 'concentration'}).columns.tolist()
#you can write the dictionary inline too if you want, if it is short and nice

renamingmorethings = {
    'parameter' : 'polutant',
    'value' : 'concentration'
}
goleta_renamed2 = goleta_renamed.rename(columns= renamingmorethings)
goleta_renamed2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2266 entries, 0 to 2265
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   location_id    2266 non-null   int64
 1   location_name  2266 non-null   object
 2   parameter      2266 non-null   object
 3   value          2266 non-null   float64
 4   unit           2266 non-null   object
 5   datetimeUtc    2266 non-null   object
 6   datetimeLocal  2266 non-null   object
 7   timezone       2266 non-null   object
 8   latitude       2266 non-null   float64
 9   longitude      2266 non-null   float64
 10  country_iso    0 non-null      float64
 11  isMobile       0 non-null      float64
 12  isMonitor      0 non-null      float64
 13  owner_name     2266 non-null   object
 14  provider       2266 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 265.7+ KB

,location_id,location_name,polutant,concentration,unit,datetime_utc,datetime_local,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,1186,Goleta,o3,0.025,ppm,2024-07-12T01:00:00+00:00,2024-07-11T18:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
1,1186,Goleta,o3,0.028,ppm,2024-07-12T02:00:00+00:00,2024-07-11T19:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
2,1186,Goleta,o3,0.029,ppm,2024-07-12T03:00:00+00:00,2024-07-11T20:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
3,1186,Goleta,o3,0.027,ppm,2024-07-12T04:00:00+00:00,2024-07-11T21:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow
4,1186,Goleta,o3,0.026,ppm,2024-07-12T05:00:00+00:00,2024-07-11T22:00:00-07:00,America/Los_Angeles,34.445301,-119.827797,NaN,NaN,NaN,Unknown Governmental Organization,AirNow

In [ ]:
# this is the 'exploration ritual' that should be ran every time we look at a new df

df.head()                  # what does a row look like
df.shape                   # how big
df.info()                  # types, and how much of each column is filled in
df.isnull().sum()          # how many values are missing, column by column
df.describe()              # what do the numbers look like
df['col'].value_counts()   # what is in the text columns