# Day 2: Session 2D - Lists & Dictionaries

Date: 09/01/2026

In [1]:
import pandas as pd

url = 'https://eds-217-essential-python.github.io/data/national_parks.csv'
data = pd.read_csv(url)

data[data['visitors'] == data['visitors'].max()] # what i wanted the whole time

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
397,Total,1009494,MULTIPOLYGON,NaN,1,NaN,NT,NC,BLRI,Blue Ridge Parkway,Parkway,871922828.0

In [14]:
data.info()
data.shape
# data.head()
data['state'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21560 entries, 0 to 21559
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               21560 non-null  object
 1   gnis_id            21560 non-null  object
 2   geometry           21560 non-null  object
 3   metadata           18848 non-null  object
 4   number_of_records  21560 non-null  int64
 5   parkname           19342 non-null  object
 6   region             21560 non-null  object
 7   state              21560 non-null  object
 8   unit_code          21560 non-null  object
 9   unit_name          21560 non-null  object
 10  unit_type          21560 non-null  object
 11  visitors           21556 non-null  float64
dtypes: float64(1), int64(1), object(10)
memory usage: 2.0+ MB

state
AZ    1623
CA    1543
AK    1040
VA    1035
NM     995
NY     995
UT     946
DC     813
CO     804
PA     736
WA     700
NC     637
FL     631
MD     608
MA     603
GA     600
TX     586
WY     521
SD     382
AR     342
HI     334
SC     323
MO     310
TN     305
MT     303
OH     302
MS     265
OR     240
NE     238
MI     231
KY     227
VI     188
AL     184
LA     181
NV     165
ND     159
IN     149
NJ     149
KS     144
ID     142
MN     126
IA     115
WV     112
ME     104
WI      90
OK      67
NH      50
IL      47
PR      39
RI      39
GU      33
CT      25
VT      20
AS      14
Name: count, dtype: int64

There are 12 columns named:

In [13]:
data.columns

Index(['year', 'gnis_id', 'geometry', 'metadata', 'number_of_records',
       'parkname', 'region', 'state', 'unit_code', 'unit_name', 'unit_type',
       'visitors'],
      dtype='object')

The state with the most entries is AZ.

In [15]:
data['state'].value_counts()

state
AZ    1623
CA    1543
AK    1040
VA    1035
NM     995
NY     995
UT     946
DC     813
CO     804
PA     736
WA     700
NC     637
FL     631
MD     608
MA     603
GA     600
TX     586
WY     521
SD     382
AR     342
HI     334
SC     323
MO     310
TN     305
MT     303
OH     302
MS     265
OR     240
NE     238
MI     231
KY     227
VI     188
AL     184
LA     181
NV     165
ND     159
IN     149
NJ     149
KS     144
ID     142
MN     126
IA     115
WV     112
ME     104
WI      90
OK      67
NH      50
IL      47
PR      39
RI      39
GU      33
CT      25
VT      20
AS      14
Name: count, dtype: int64

The number_of_records column only has values 1 or NA

In [16]:
data.describe()

       number_of_records      visitors
count            21560.0  2.155600e+04
mean                 1.0  1.277105e+06
std                  0.0  1.190148e+07
min                  1.0  0.000000e+00
25%                  1.0  3.912475e+04
50%                  1.0  1.552190e+05
75%                  1.0  6.081438e+05
max                  1.0  8.719228e+08

There are 0 visitors at Lake Roosevelt in 1941, which is surely not accurate because it looks beautiful.

In [17]:
data.head()

,year,gnis_id,geometry,metadata,number_of_records,parkname,region,state,unit_code,unit_name,unit_type,visitors
0,1904,1163670,POLYGON,NaN,1,Crater Lake,PW,OR,CRLA,Crater Lake National Park,National Park,1500.0
1,1941,1531834,MULTIPOLYGON,NaN,1,Lake Roosevelt,PW,WA,LARO,Lake Roosevelt National Recreation Area,National Recreation Area,0.0
2,1961,2055170,MULTIPOLYGON,NaN,1,Lewis and Clark,PW,WA,LEWI,Lewis and Clark National Historical Park,National Historical Park,69000.0
3,1935,1530459,MULTIPOLYGON,NaN,1,Olympic,PW,WA,OLYM,Olympic National Park,National Park,2200.0
4,1982,277263,POLYGON,NaN,1,Santa Monica Mountains,PW,CA,SAMO,Santa Monica Mountains National Recreation Area,National Recreation Area,468144.0

There are 2218 empty cells for parkname.

In [18]:
data.isnull().sum()

year                    0
gnis_id                 0
geometry                0
metadata             2712
number_of_records       0
parkname             2218
region                  0
state                   0
unit_code               0
unit_name               0
unit_type               0
visitors                4
dtype: int64

In [42]:
max = data['visitors'].max()

data.loc[data['visitors'].idxmax(), 'parkname']

nan